name: cubic_sleep
channels:
  - conda-forge
  - defaults
dependencies:
  - arviz=0.21.0
  - aws-c-auth=0.8.6
  - aws-c-cal=0.8.7
  - aws-c-common=0.12.0
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.4
  - aws-c-http=0.9.4
  - aws-c-io=0.17.0
  - aws-c-mqtt=0.12.2
  - aws-c-s3=0.7.13
  - aws-c-sdkutils=0.2.3
  - aws-checksums=0.2.3
  - aws-crt-cpp=0.31.0
  - aws-sdk-cpp=1.11.510
  - blas=1.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2025.1.31
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.5.2
  - cairo=1.18.4
  - cloudpickle=3.1.1
  - cons=0.4.6
  - contourpy=1.3.1
  - cpp-expected=1.1.0
  - cycler=0.12.1
  - distutils-activate-mingw=2.3
  - etuples=0.3.9
  - filelock=3.18.0
  - fmt=11.1.4
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.56.0
  - freetype=2.13.3
  - fribidi=1.0.10
  - getopt-win32=0.1
  - graphite2=1.3.13
  - graphviz=12.2.1
  - gts=0.7.6
  - h5netcdf=1.6.1
  - h5py=3.13.0
  - harfbuzz=10.4.0
  - hdf5=1.14.3
  - icu=75.1
  - intel-openmp=2024.2.1
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20250127.1
  - libaec=1.1.3
  - libarchive=3.7.7
  - libarrow=19.0.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.12.1
  - libdeflate=1.23
  - libexpat=2.6.4
  - libffi=3.4.6
  - libgd=2.3.3
  - libglib=2.84.0
  - libgoogle-cloud=2.36.0
  - libgoogle-cloud-storage=2.36.0
  - libgrpc=1.71.0
  - libhwloc=2.11.2
  - libiconv=1.18
  - libintl=0.22.5
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblzma=5.6.4
  - liblzma-devel=5.6.4
  - libmamba=2.0.8
  - libpng=1.6.47
  - libprotobuf=5.29.3
  - libpython=2.3
  - libre2-11=2024.07.02
  - libsolv=0.7.30
  - libsqlite=3.49.1
  - libssh2=1.11.1
  - libtiff=4.7.0
  - libutf8proc=2.10.0
  - libwebp-base=1.5.0
  - libxcb=1.16
  - libxml2=2.13.7
  - libzlib=1.3.1
  - llvmlite=0.43.0
  - logical-unification=0.4.6
  - lz4-c=1.10.0
  - lzo=2.10
  - m2w64-binutils=2.25.1
  - m2w64-bzip2=1.0.6
  - m2w64-crt-git=5.0.0.4636.2595836
  - m2w64-gcc=5.3.0
  - m2w64-gcc-ada=5.3.0
  - m2w64-gcc-fortran=5.3.0
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gcc-objc=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-headers-git=5.0.0.4636.c0ad18a
  - m2w64-isl=0.16.1
  - m2w64-libiconv=1.14
  - m2w64-libmangle-git=5.0.0.4509.2e5a9a2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - m2w64-make=4.1.2351.a80a8b8
  - m2w64-mpc=1.0.3
  - m2w64-mpfr=3.1.4
  - m2w64-pkg-config=0.29.1
  - m2w64-toolchain=5.3.0
  - m2w64-toolchain_win-64=2.5.0
  - m2w64-tools-git=5.0.0.4592.90b8472
  - m2w64-windows-default-manifest=6.4
  - m2w64-winpthreads-git=5.0.0.4634.697f757
  - m2w64-zlib=1.2.8
  - mamba=2.0.8
  - markdown-it-py=3.0.0
  - matplotlib-base=3.10.1
  - mdurl=0.1.2
  - minikanren=1.0.3
  - mkl=2024.2.2
  - mkl-devel=2024.2.2
  - mkl-include=2024.2.2
  - mkl-service=2.4.2
  - msys2-conda-epoch=20160418
  - multipledispatch=0.6.0
  - munkres=1.1.4
  - nlohmann_json=3.11.3
  - numba=0.60.0
  - numpy=1.24.4
  - nutpie=0.13.2
  - openjpeg=2.5.3
  - openssl=3.4.1
  - orc=2.1.1
  - packaging=24.2
  - pandas=2.2.3
  - pango=1.56.3
  - pcre2=10.44
  - pillow=10.4.0
  - pip=25.0.1
  - pixman=0.44.2
  - pthread-stubs=0.4
  - pthreads-win32=2.9.1
  - pyarrow-core=19.0.1
  - pygments=2.19.1
  - pymc=5.17.0
  - pymc-base=5.17.0
  - pyparsing=3.2.3
  - pytensor=2.23.0
  - pytensor-base=2.25.5
  - python=3.11.9
  - python-dateutil=2.9.0.post0
  - python-graphviz=0.20.3
  - python-tzdata=2025.2
  - python_abi=3.11
  - pytz=2024.1
  - qhull=2020.2
  - re2=2024.07.02
  - reproc=14.2.5.post0
  - reproc-cpp=14.2.5.post0
  - rich=13.9.4
  - scipy=1.15.2
  - setuptools=75.8.2
  - simdjson=3.12.2
  - six=1.17.0
  - snappy=1.2.1
  - spdlog=1.15.1
  - tbb=2021.13.0
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - toolz=1.0.0
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - unicodedata2=16.0.0
  - vc=14.3
  - vc14_runtime=14.42.34438
  - vs2015_runtime=14.42.34438
  - vs2019_win-64=19.29.30139
  - vswhere=3.1.7
  - wheel=0.45.1
  - xarray=2025.3.0
  - xarray-einstats=0.8.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxpm=3.5.17
  - xorg-libxt=1.3.0
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.6.4
  - xz-tools=5.6.4
  - yaml-cpp=0.8.0
  - zstd=1.5.7
  - pip:
      - sdeint==0.3.0
